sapobroker.lo: /broker/clients/php-ext-component/sapobroker.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/broker/clients/php-ext-component $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /broker/clients/php-ext-component/sapobroker.c -o sapobroker.lo 
$(phplibdir)/sapobroker.la: ./sapobroker.la
	$(LIBTOOL) --mode=install cp ./sapobroker.la $(phplibdir)

./sapobroker.la: $(shared_objects_sapobroker) $(SAPOBROKER_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_sapobroker) $(SAPOBROKER_SHARED_LIBADD)

